version: '3.5'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-11.5-alpine}
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    shm_size: '2gb'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
  multisig-coordination-server:
    build:
      context: ..
      target: multisig-coordination-server
    environment:
      - BIND_ADDRESS='0.0.0.0'
      - DB_CONNECTION_STRING=postgresql://postgres:notForProduction!@postgres:5432/cexplorer
      - LOGGER_LEVEL=debug
      - PORT=8080
    expose:
      - 8080
    ports:
      - ${PORT:-8080}:8080
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    volumes:
      - ../config/network/${NETWORK:-mainnet}:/config
      - node-ipc:/node-ipc
secrets:
  postgres_db:
    file: ./config/secrets/postgres_db
  postgres_password:
    file: ./config/secrets/postgres_password
  postgres_user:
    file: ./config/secrets/postgres_user
volumes:
  node-db:
  node-ipc:
  postgres-data:
